name: Format checking
on:
  pull_request:
    branches:
      - lab1
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cashe: npm
          node-version: 14
      - run: npm ci && npm run lint && npm run lintcss && npm run prettiercheck
